[build]
rustflags = ["-Z", "threads=8",
 # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
]

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"

[patch.crates-io]
# bevy = { path = "../bevy-fork" }
# bevy = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# gltf = { git = "https://github.com/gltf-rs/gltf.git", branch = "main" }

# bevy_math = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_ecs = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_internal = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }

# bevy_reflect = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_app = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_color = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_log = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_platform = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_render = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_utils = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }

# bevy_asset = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_mesh = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_image = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_text = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_shader = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_core_pipeline = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_camera = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_sprite = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_picking = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_light = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_gizmos = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_sprite_render = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_ui = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_ui_render = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_pbr = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_transform = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_window = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_input = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_input_focus = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_winit = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_gltf = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_tasks = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_scene = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_remote = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_time = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_diagnostic = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
